project:
  type: website

website:
  title: "Physical Profiles"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: story.qmd
        text: Story
      - href: exploration.qmd
        text: Exploration
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
