project:
  type: website

website:
  title: "Physical Profiles"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: story.qmd
        text: Positional Archetypes
      - href: bmi.qmd
        text: Body Mass
      - href: exploration.qmd
        text: Positional Breakdown
      - href: player-explorer.qmd
        text: Player Explorer
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
